version: '2.2'
services:
  news-service:
    build: .
    image: kommcenta/news-service:v1.0.0
    ports:
      - "8090:5000"
    volumes:
      - .:/app
    # environment:
    #   FLASK_ENV: development
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.2
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
volumes:
  esdata01:
    driver: local

networks:
  esnet: